Blog/Controllers/GuestPageController.cs
﻿using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogData.Reviews.Models;
using BlogData.Repository;
using BlogData.Repository.ReviewsRepository;
using BlogData.Repository.Abstract;

namespace Blog.Controllers
{

    public class GuestPageController : Controller
    {
        /// <summary>
        /// Contains an operations which process data about users reviews which are located in database 
        /// </summary>
        private IReviewsRepository _repository = new ReviewsRepository(ConfigurationManager.ConnectionStrings["BlogDataContext"].ConnectionString);

        /// <summary>
        /// Shows guest page and sends users reviews from database to view
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(_repository.GetGuestPageReviews);
        }

        /// <summary>
        /// Processes data about added review and add new review to database
        /// After processing data, shows page with information about user's review 
        /// </summary>
        /// <param name="review">Added review</param>
        /// <returns></returns>
        public ActionResult AddReview(Review review)
        {
            if (HttpContext.Request.HttpMethod == "POST")
            {
                if (ModelState.IsValid)
                {
                    ViewBag.Answer = "Ваш комментарий будет рассмотрен администратором сайта, ожидайте.";
                    _repository.Add(review);
                    return View();
                }
            }
            return View("~/Views/GuestPage/Index.cshtml", _repository.GetAll);
        }
    }
}

Blog/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    public class QuestionnaireController : Controller
    {
        /// <summary>
        /// Shows the questionnairy page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Processes data from quastionnairy form and shows information about user's questionnairy
        /// </summary>
        /// <param name="data">Data from questionnairy form</param>
        /// <returns></returns>
        public ActionResult AddQuestionnairy(QuestionnaireData data)
        {
            if (HttpContext.Request.RequestType == "POST")
            {
                ViewBag.Name = data.Name;
                return View();
            }

            return View("~/Views/Questionnairy/Index.cshtml");
        }
    }
}

Blog/Views/_Layout.cshtml
@using Blog.Helpers.BasicLayoutHelpers;

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Blog</title>
    <link href="~/Content/MainPageStyles.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/GuestPageStyles.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/BasicLayoutStyles.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/QuestionnairePageStyles.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/NewsReportOfferPageStyles.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/ValidationErrorsStyles.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/NewReportPageStyles.css" type="text/css" rel="stylesheet"/>
    <script src="~/Script/LogoAnimation.js" type="text/javascript"></script>
</head>
<body>
    <header id="header">
        <div class="site-logo-box">
            <img id="logo" src="~/Images/site-icon.png"/>
        </div>
        <h1>Блог обо всём</h1>
    </header>
    <main>
        <div class="content">
            @RenderBody()
        </div>
        <aside>
            @Html.ActionList(new MvcHtmlString[] {
                @Html.ActionLink("Главная", "Index", "Home"),
                @Html.ActionLink("Гостевая", "Index", "GuestPage"),
                @Html.ActionLink("Анкета", "Index", "Questionnaire")
                 })
            @RenderSection("ExtendedData", false)
            @RenderSection("Voting", false)
        </aside>
    </main>
    <footer>
        <p>.Net Blog Kharkov &#169 2018</p>
        <a href="#header">Перейти в начало</a>
    </footer>
</body>
</html>