Blog/Controllers/VotingsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BlogData.Repository.Abstract;
using BlogData.Repository.VotingsRepositories;
using BlogData.Votings;

namespace Blog.Controllers
{
    public class VotingsController : Controller
    {
        /// <summary>
        /// Conatains voting information
        /// </summary>
        IVotingFormCatsRepository _repository = new VotingAboutCatsRepository(ConfigurationManager.ConnectionStrings["BlogDataContext"].ConnectionString);

        /// <summary>
        /// Shows voting is user didn't vote
        /// Shows voting result if user has already voted
        /// </summary>
        /// <returns></returns>
        public ActionResult Voting()
        {
            bool? isAlreadyVoted = Convert.ToBoolean(Session["IsVoted"]);
            var voting = _repository.GetVoting;
            Session["Voting"] = voting;

            if (isAlreadyVoted == true)
            {
                bool isLike = Convert.ToBoolean(Session["isLike"]);
                ViewBag.Like = isLike;
                return PartialView("~/Views/Votings/VotingResult.cshtml", voting);
            }
            else
            {
                return PartialView("~/Views/Votings/Voting.cshtml");
            }

        }

        /// <summary>
        /// Adds new vote to voting repository
        /// After addition shows start page
        /// </summary>
        /// <param name="votingVariant">User's vote</param>
        /// <returns>Redirect to start page</returns>
        [HttpGet]
        public ActionResult AddVote(bool votingVariant)
        {
            VotingAboutCats voting = (VotingAboutCats)Session["Voting"];

            if (votingVariant)
            {
                Session["isLike"] = true;
                voting.PeopleWhoLoveCatsCount++;
            }
            else
            {
                Session["isLike"] = false;
                voting.PeopleWhoDontLoveCatsCount++;
            }

            _repository.Update(voting);
            Session["IsVoted"] = true;
            return RedirectToAction("Index", "Home");
        }
    }
}

Blog/Views/Votings/Voting.cshtml
<div class="voting">
    <img src="~/Images/voting-cat.jpg" alt="cat"/>

    @using (@Html.BeginForm("AddVote", "Votings", FormMethod.Get, new { @class = "voting-form" }))
    {
        <h2>Котиков любите?</h2>
        <p>
            <input type="radio" name="votingVariant" value="true" />
            Да
        </p>
        <p>
            <input type="radio" name="votingVariant" value="false" />
            Нет
        </p>

        <div class="voting-form-submit-line">
            <input type="submit" value="Голосовать" />
        </div>

    }
</div>

Blog/Views/Votings/VotingResult.cshtml
@model BlogData.Votings.VotingAboutCats

<div class="voting">
    @if ((bool)ViewBag.Like)
    {
        <img src="~/Images/funny-cat.jpg" alt="cat" />
    }
    else
    {
        <img src="~/Images/sad-cat.jpg" alt="cat" />
    }

    <h2>Любите котиков?</h2>
    @if ((bool)ViewBag.Like)
    {
        <p class="voting-user-choose">@Model.PeopleWhoLoveCatsCount человек сказали "Да!"</p>
        <p>@Model.PeopleWhoDontLoveCatsCount человек сказали "Нет!"</p>
    }
    else
    {
        <p>@Model.PeopleWhoLoveCatsCount человек сказали "Да!"</p>
        <p class="voting-user-choose">@Model.PeopleWhoDontLoveCatsCount человек сказали "Нет!"</p>
    }

</div>