Blog/Controllers/NewsReportOfferController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using BlogData.News.Models;
using BlogData.Repository.Context;
using BlogData.Repository.Abstract;
using BlogData.Repository.NewsRepository;

namespace Blog.Controllers
{
    public class NewsReportOfferController : Controller
    {
        /// <summary>
        /// Contains the operations which process data about news reports which are located in database
        /// </summary>
        private INewsRepository _repository = new NewsRepository(ConfigurationManager.ConnectionStrings["BlogDataContext"].ConnectionString);
        
        /// <summary>
        /// Shows the news offer page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Processes data about offered news report and adds new news report to database
        /// After that shows result about addition new news report
        /// </summary>
        /// <param name="newReport">News report new addition</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddNewsReport(NewsReport newReport)
        {
            if (ModelState.IsValid)
            {
                _repository.Add(newReport);
                ViewBag.Name = newReport.Author;
                return View();
            }
            else
            {
                return View("~/Views/NewsReportOffer/Index.cshtml");
            }
        }
    }
}

Blog/Views/NewsReportOffer/AddNewsReport.cshtml
@model BlogData.News.Models.NewsReport

@{
    ViewBag.Title = "AddNewsReport";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>Спасибо за предложенную новость!</h2>
<p>Новость будет рассмотрена в ближайшее время</p>

Blog/Views/NewsReportOffer/Index.cshtml
@model BlogData.News.Models.NewsReport

@{
    ViewBag.Title = "Your news...";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="news-offer-container">
    @using (@Html.BeginForm("AddNewsReport", "NewsReportOffer", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary();
        <div class="news-offer-container-input-line">
            @Html.LabelFor(x => x.Author)
            @Html.TextBoxFor(x => x.Author)
        </div>
        <div class="news-offer-container-input-line">
            @Html.LabelFor(x => x.AuthorEmail)
            @Html.TextBoxFor(x => x.AuthorEmail)
        </div>
        <div class="news-offer-container-input-line">
            @Html.LabelFor(x => x.ReportHeader)
            @Html.TextAreaFor(x => x.ReportHeader)
        </div>
        <div class="news-offer-container-input-line">
            @Html.LabelFor(x => x.ReportContent)
            @Html.TextAreaFor(x => x.ReportContent)
        </div>
        <div class="news-offer-container-input-line">
            @Html.LabelFor(x => x.ReportTags)
            @Html.TextAreaFor(x => x.ReportTags)
        </div>
    <div class="news-offer-container-submit">
        <input type="submit" value="Предложить" />
    </div>

    }
</div>